disable legacy_rc supervision for now, as it is currently fucked

diff --git a/etc/freebsd/1 b/etc/freebsd/1
--- a/etc/freebsd/1
+++ b/etc/freebsd/1
@@ -10,16 +10,16 @@ mount -t procfs proc /proc
 zfs set readonly=off rpool/BOOTENV/sunshine
 zfs mount -a
 
-rm -f /service/wpa_supplicant* /service/dhclient*
+rm -rf /service/wpa_supplicant* /service/dhclient*
 
-#/bin/sh /etc/rc autoboot
-#if test $? -ne 0; then
-#  # /etc/rc crashed, start emergency shell.
-#  echo '/etc/rc failed. Press <enter> for emergency shell...'
-#  read input
-#  sh -p
-#  exec reboot
-#fi
+/bin/sh /etc/rc autoboot
+if test $? -ne 0; then
+  # /etc/rc crashed, start emergency shell.
+  echo '/etc/rc failed. Press <enter> for emergency shell...'
+  read input
+  sh -p
+  exec reboot
+fi
 touch /etc/runit/stopit
 chmod 0 /etc/runit/stopit
 sh -p
