Move from 3-stage to 4-stage init (Stage 1 remains sysinit, stage 2 is /etc/rc, etc.)

diff --git a/distrib/etc/runit/2 b/distrib/etc/runit/2
--- a/distrib/etc/runit/2
+++ b/distrib/etc/runit/2
@@ -1,6 +1,18 @@
 #!/bin/sh
+# system one time tasks part two: legacy rc
 
-PATH=/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin
+PATH=/sbin:/bin:/usr/sbin:/usr/bin
+trap : 2
+trap : 3
 
-exec env - PATH=$PATH \
-runsvdir -P /service 'log: ...........................................................................................................................................................................................................................................................................................................................................................................................................'
+/bin/sh /etc/rc autoboot
+if test $? -ne 0; then
+  # /etc/rc crashed, start emergency shell.
+  echo '/etc/rc failed. Press <enter> for emergency shell...'
+  read input
+  sh -p
+  exec reboot
+fi
+
+touch /etc/runit/stopit
+chmod 0 /etc/runit/stopit
